create extension if not exists pgcrypto;

create table if not exists public.lunchdrops (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  location_id text not null,
  recipient_name text not null,
  sender_name text not null,
  amount integer not null check (amount between 1 and 100),
  message text not null default '',
  special text,
  chosen_location_id text,
  status text not null default 'created'
    check (status in ('created','opened','demo_claimed','connected_claimed','cancelled')),
  sender_secret_hash text not null,
  reward_id text,
  created_at timestamptz not null default now(),
  opened_at timestamptz,
  demo_claimed_at timestamptz,
  connected_claimed_at timestamptz,
  cancelled_at timestamptz,
  expires_at timestamptz not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.lunchdrop_events (
  id bigint generated by default as identity primary key,
  lunchdrop_id uuid not null references public.lunchdrops(id) on delete cascade,
  event_type text not null,
  event_meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists lunchdrops_code_idx on public.lunchdrops(code);
create index if not exists lunchdrops_created_at_idx on public.lunchdrops(created_at desc);
create index if not exists lunchdrop_events_drop_idx on public.lunchdrop_events(lunchdrop_id, created_at desc);

alter table public.lunchdrops enable row level security;
alter table public.lunchdrop_events enable row level security;

-- Intentionally no anon/authenticated policies.
-- LunchDrop accesses these tables from server routes with the Supabase service-role key.

create or replace function public.set_lunchdrop_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists lunchdrops_updated_at on public.lunchdrops;
create trigger lunchdrops_updated_at
before update on public.lunchdrops
for each row execute function public.set_lunchdrop_updated_at();
